default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: <%= ENV.fetch("SOLID_QUEUE_QUEUES", "default") %>
      threads: <%= ENV.fetch("SOLID_QUEUE_THREADS", 3) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
